name: Build and push to Docker Hub

env:
  VERSION:
  REPO_NAME:

on:
  push:
    branches:
      - 'master'
    tags: [ 'v*.*.*-*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_AUTOMATION_USERNAME }}
          password: ${{ secrets.DOCKERHUB_AUTOMATION_PASSWORD }}

      - name: Get repository name
        id: repo_name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)" >> $GITHUB_ENV


      - name: Extract version from Changelog.md
        id: get_version
        run: |
          # Check if Changelog.md exists
          CHANGELOG_FILE=$(ls *Changelog.md 2>/dev/null || true)
      
          if [ -z "$CHANGELOG_FILE" ]; then
            echo "No Changelog.md file found in the current directory"
            exit 1
          fi
      
          # Extract the version from the changelog (assuming it's in the first line and starts with 'v')
          VERSION=$(grep -oP '^v[0-9]+\.[0-9]+\.[0-9]+' "$CHANGELOG_FILE" | head -n 1)
      
          if [ -z "$VERSION" ]; then
            echo "No version found in $CHANGELOG_FILE"
            exit 1
          fi
      
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build and tag the Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_AUTOMATION_USERNAME }}/${{ github.repository }}:${{ env.VERSION }} .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_AUTOMATION_USERNAME }}/${{ github.repository }}:${{ env.VERSION }}