name: Build and push to Docker Hub

env:
  VERSION:
  REPO_NAME:

on:
  push:
    branches:
      - 'master'
    tags: [ 'v*.*.*-*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_AUTOMATION_USERNAME }}
          password: ${{ secrets.DOCKERHUB_AUTOMATION_PASSWORD }}

      - name: Get repository name
        id: repo_name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v2

      - run: ls

      - name: Extract version from Changelog.md
        id: get_version
        run: |
          # Extract the version from the changelog file
          VERSION=$(ls *Changelog.md | grep -oP '^[^ ]+' | cut -c2-)

          if [ -z "$VERSION" ]; then
            echo "No version found in Changelog.md"
            exit 1
          fi

          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build and tag the Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_AUTOMATION_USERNAME }}/${{ github.repository }}:${{ env.VERSION }} .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_AUTOMATION_USERNAME }}/${{ github.repository }}:${{ env.VERSION }}